version: '3'
services:
    angular-frontend:
        build:
            context: ./containers/angular-frontend
        ports: 
            - "4200:80"
        links:
            - golang-api-server
    nextjs-frontend:
        build:
            context: ./containers/nextjs-frontend
        ports:
            - "3000:3000"
        links:
            - java-api-server
        environment:
            - NODE_ENV=production
    golang-api-server:
        build:
            context: ./containers/golang-api-server
        expose:
            - "8080"
        ports:
            - "8080:8080"
    java-api-server:
        build:
            context: ./containers/java-api-server
        expose:
            - "8081"
        ports:
            - "8081:8081"
