version: '3'
services:
    angular-frontend:
        build:
            dockerfile: Dockerfile
            context: ./containers/angular-frontend
        ports: 
            - "4200:80"
        links:
            - golang-api-server
    nextjs-frontend:
        build:
            dockerfile: Dockerfile
            context: ./containers/nextjs-frontend
        ports:
            - "3000:3000"
        links:
            - golang-api-server
        environment:
            - NODE_ENV=production
    golang-api-server:
        build:
            dockerfile: Dockerfile
            context: ./containers/golang-api-server
        expose:
            - "8080"

