version: '3'
volumes:
    node_modules:
    gradle:
    java_server_build:
services:
    angular-frontend:
        image: node:10.13
        command: bash -c "npm install && npm run dev"
        volumes:
            - ./containers/angular-frontend:/src
        working_dir: /src
        ports: 
            - "4200:4200"
        links:
            - python-api-server
    nextjs-frontend:
        image: node:10.13
        command: bash -c "npm install && npm run dev"
        volumes:
            - ./containers/nextjs-frontend:/front
            - node_modules:/front/node_modules
        working_dir: /front
        ports: 
            - "3000:3000"
        links:
            - java-api-server
    golang-api-server:
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/golang-api-server
        command: fresh
        expose:
            - "8080"
        ports: 
            - "8080:8080"
        volumes:
            - ./containers/golang-api-server:/src
    java-api-server:
        image: openjdk:11-jdk-slim-sid
        expose:
            - "8081"
        ports:
            - "8081:8081"
        volumes:
            - ./containers/java-api-server:/src
            - gradle:/root/.gradle
            - java_server_build:/root/build
        working_dir: /src
        command: bash -c "./gradlew build --continuous & ./gradlew bootRun"
    python-api-server:
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/python-api-server
        expose:
            - "8000"
        ports: 
            - "8000:8000"
        volumes:
            - ./containers/python-api-server:/src